### ISSUE TITLE
Index.html file not found

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.material#1]
After installation it only says that the index.html file is missing when I try to use it.

**Comment by GermanBluefox** [comment]
How you installed that? It cannot be installed from git. Only from npm.

**Comment by Xyolyp** [comment]
I installed it from git. I'll try the npm installation now. Maybe you could
add a short note to the readme.md

Bluefox <notifications@github.com> schrieb am Fr., 19. Jan. 2018, 21:04:
