### ISSUE TITLE
[FeatureRequest] Show more Info about an Item which is currently in editing

### ISSUE THREAD

**Issue by Hypnos3** [ioBroker/ioBroker.material#10]
Please add a card (maybe at the bottom) to the edit screen for an "object"/"Box" which show more information about what the object is, which I'm currenlty edit.

For an IO Broker Object the ID and original name could be shown:
![image](https://user-images.githubusercontent.com/12692680/43905367-4310d47e-9bf1-11e8-9cf2-058ecff73d6d.png)

This is only for information purpose to better identify what I'm currently editing.

The name itself of the object could be changed in that dialog:
![image](https://user-images.githubusercontent.com/12692680/43906160-e54514e8-9bf2-11e8-8f4d-c9e824cb7c6a.png)
Then it will be hard to identify what is the original source from IOBorker objects.

In other situations different channels are displayed (Example a smoke detector) and it is in the edit View sometimes hard to identify which of the channels of the element I'm currently editing:
![image](https://user-images.githubusercontent.com/12692680/43904991-5977b99a-9bf0-11e8-8a15-a4181451c346.png)
![image](https://user-images.githubusercontent.com/12692680/43904855-0a87a886-9bf0-11e8-8d81-9f096d8e3c5b.png)
![image](https://user-images.githubusercontent.com/12692680/43905028-7019497a-9bf0-11e8-80b4-2117102851fa.png)
![image](https://user-images.githubusercontent.com/12692680/43905047-7ad8e956-9bf0-11e8-8eeb-c62775fa421b.png)

**Comment by GermanBluefox** [comment]
Nice request.

**Comment by Hypnos3** [comment]
Thank You!
