### ISSUE TITLE
weather text overlap

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.material#13]
in the weather widget the text is overlapping, i use the daswetter adapter
![2018-08-17_05h02_07](https://user-images.githubusercontent.com/6328382/44245839-37bf6500-a1db-11e8-840e-3ff67635029d.png)
![2018-08-17_05h02_23](https://user-images.githubusercontent.com/6328382/44245845-3beb8280-a1db-11e8-8b9c-b2f3a2a9aeb3.png)

**Comment by GermanBluefox** [comment]
Looks awful... :(
