### ISSUE TITLE
yeelight support

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.material#14]
i tried to add thee yeelights to material but it failed. i think the roles are correct. can you give me a tip where my mistake is?!  here is an overview of the lights
![2018-08-20_06h40_00](https://user-images.githubusercontent.com/6328382/44320797-6db35200-a444-11e8-868e-af28baffdf06.png)

**Comment by GermanBluefox** [comment]
Try to change level.rgb => level.color.rgb

**Comment by GermanBluefox** [comment]
Can you export your tree here?

**Comment by MeisterTR** [comment]
changed nothing : here are a  peace of the object json:

"yeelight-2.0.color-Yeelight_Ecke__": {
        "type": "device",
        "common": {
            "name": "color",
            "icon": "/icons/color.png"
        },
        "native": {
            "sid": "Yeelight_Ecke__",
            "type": "color"
        },
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405156,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__",
        "acl": {
            "object": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.info": {
        "type": "channel",
        "common": {
            "name": "info"
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405156,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.info",
        "acl": {
            "object": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control": {
        "type": "device",
        "common": {
            "name": "control"
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405156,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control",
        "acl": {
            "object": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.info.com": {
        "common": {
            "name": "Command",
            "role": "state",
            "write": false,
            "read": true,
            "type": "string"
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.info.com",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.info.connect": {
        "common": {
            "name": "Connect",
            "role": "indicator.connected",
            "write": false,
            "read": true,
            "type": "boolean"
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.info.connect",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.info.IPAdress": {
        "common": {
            "name": "IP",
            "role": "state",
            "write": false,
            "read": true,
            "type": "string"
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.info.IPAdress",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.info.Port": {
        "common": {
            "name": "Port",
            "role": "state",
            "write": false,
            "read": true,
            "type": "number",
            "custom": {
                "material": {
                    "admin": {
                        "enabled": true,
                        "useCustom": false,
                        "name": "info"
                    }
                }
            }
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.info.Port",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___": {
        "type": "device",
        "common": {
            "name": "ceiling1",
            "icon": "/icons/ceiling1.png"
        },
        "native": {
            "sid": "Yeelightv____KLavie___",
            "type": "ceiling1"
        },
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___",
        "acl": {
            "object": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info": {
        "type": "channel",
        "common": {
            "name": "info"
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info",
        "acl": {
            "object": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control": {
        "type": "channel",
        "common": {
            "name": "control"
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control",
        "acl": {
            "object": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.com": {
        "common": {
            "name": "Command",
            "role": "state",
            "write": false,
            "read": true,
            "type": "string"
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.com",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.connect": {
        "common": {
            "name": "Connect",
            "role": "indicator.connected",
            "write": false,
            "read": true,
            "type": "boolean"
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405158,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.connect",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.IPAdress": {
        "common": {
            "name": "IP",
            "role": "state",
            "write": false,
            "read": true,
            "type": "string"
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405160,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.IPAdress",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.Port": {
        "common": {
            "name": "Port",
            "role": "state",
            "write": false,
            "read": true,
            "type": "number"
        },
        "type": "state",
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405160,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.info.Port",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.power": {
        "type": "state",
        "common": {
            "name": "power",
            "role": "switch",
            "write": true,
            "read": true,
            "type": "boolean",
            "smartName": {
                "de": "Hshd.er",
                "smartType": "LIGHT"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405182,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.power",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.active_bright": {
        "type": "state",
        "common": {
            "name": "active_bright",
            "role": "level.dimmer",
            "write": true,
            "read": true,
            "type": "number",
            "min": 0,
            "max": 100,
            "unit": "%",
            "smartName": {
                "de": "Hshd.er",
                "smartType": "LIGHT",
                "byON": "-"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405182,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.active_bright",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.ct": {
        "type": "state",
        "common": {
            "name": "ct",
            "role": "level.color.temperature",
            "write": true,
            "read": true,
            "type": "number",
            "min": 2600,
            "max": 6500,
            "unit": "K",
            "smartName": {
                "de": "Hshd.er",
                "smartType": "LIGHT"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405183,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.ct",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.moon_mode": {
        "type": "state",
        "common": {
            "name": "moon_mode",
            "role": "switch",
            "write": true,
            "read": true,
            "type": "boolean"
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405183,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.moon_mode",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.color_mode": {
        "type": "state",
        "common": {
            "name": "color_mode",
            "role": "switch",
            "write": true,
            "read": true,
            "type": "boolean"
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405183,
        "_id": "yeelight-2.0.ceiling1-Yeelightv____KLavie___.control.color_mode",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control.power": {
        "type": "state",
        "common": {
            "name": "ON_LIGHT",
            "role": "switch.light",
            "write": true,
            "read": true,
            "type": "boolean",
            "smartName": {
                "de": "Test Peter ",
                "smartType": "LIGHT"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405190,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control.power",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control.active_bright": {
        "type": "state",
        "common": {
            "name": "BRIGHTNESS",
            "role": "level.dimmer",
            "write": true,
            "read": true,
            "type": "number",
            "min": 0,
            "max": 100,
            "unit": "%",
            "smartName": {
                "de": "Test Peter ",
                "smartType": "LIGHT",
                "byON": "-"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405194,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control.active_bright",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control.ct": {
        "type": "state",
        "common": {
            "name": "TEMPERATURE",
            "role": "level.color.temperature",
            "write": true,
            "read": true,
            "type": "number",
            "min": 1700,
            "max": 6500,
            "unit": "K",
            "smartName": {
                "de": "Test Peter ",
                "smartType": "LIGHT"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405194,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control.ct",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control.rgb": {
        "type": "state",
        "common": {
            "name": "RGB",
            "role": "level.color.rgb",
            "write": true,
            "read": true,
            "type": "string",
            "custom": {
                "material": {
                    "admin": {
                        "enabled": true,
                        "useCustom": false,
                        "name": "control"
                    }
                }
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405194,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control.rgb",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control.color_mode": {
        "type": "state",
        "common": {
            "name": "color_mode",
            "role": "switch",
            "write": true,
            "read": true,
            "type": "boolean"
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405194,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control.color_mode",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control.hue": {
        "type": "state",
        "common": {
            "name": "HUE",
            "role": "level.color.hue",
            "write": true,
            "read": true,
            "type": "number",
            "min": 0,
            "max": 360,
            "smartName": {
                "de": "Test Peter ",
                "smartType": "LIGHT"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405194,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control.hue",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },
    "yeelight-2.0.color-Yeelight_Ecke__.control.sat": {
        "type": "state",
        "common": {
            "name": "SATURATION",
            "role": "level.color.saturation",
            "write": true,
            "read": true,
            "type": "number",
            "min": 0,
            "max": 100,
            "smartName": {
                "de": "Test Peter ",
                "smartType": "LIGHT"
            }
        },
        "native": {},
        "from": "system.adapter.yeelight-2.0",
        "ts": 1530936405200,
        "_id": "yeelight-2.0.color-Yeelight_Ecke__.control.sat",
        "acl": {
            "object": 1636,
            "state": 1636,
            "owner": "system.user.admin",
            "ownerGroup": "system.group.administrator"
        }
    },

**Comment by GermanBluefox** [comment]
FYI: 
![image](https://user-images.githubusercontent.com/4582016/44359157-4f3a6e80-a4b7-11e8-8e84-81b4012902ff.png)

**Comment by MeisterTR** [comment]
und wieder was gelernt..

[yeelight.zip](https://github.com/ioBroker/ioBroker.material/files/2303549/yeelight.zip)
hier mal die unverbastelten objekte wie sie vom Adapter erzeugt werden

**Comment by Ilovegym66** [comment]
hier mal zum Vergleich oder als Add meine Objekte vom Yeelight Stripe
[yeelight-2.0.stripe-LichtSchrank.json.zip](https://github.com/ioBroker/ioBroker.material/files/2313354/yeelight-2.0.stripe-LichtSchrank.json.zip)

**Comment by MeisterTR** [comment]
something new?

**Comment by GermanBluefox** [comment]
Now it should work

**Comment by MeisterTR** [comment]
works fine thanks, ct support would be great :)

**Comment by GermanBluefox** [comment]
CT is implemented
