### ISSUE TITLE
Mobil nicht alle Geräte angezeigt

### ISSUE THREAD

**Issue by Gerrni** [ioBroker/ioBroker.material#15]
habe einige Räume die auch angezeigt werden. Allerdings der letzte am Smartphone und Tablet nur in Ansicht Hochkant. Die Raumübersicht habe ich zum Ende gescrollt, kein "Wohnzimmer" zu finden. Entdeckt unter Android. 
Ebenso werden Geräte die per deConz angebunden sind per Smartphone und Tablet nicht angezeigt
Per PC ist alles zu sehen, sogar auch über ioBroker.pro.

**Comment by GermanBluefox** [comment]
>sogar auch über ioBroker.pro

Zwischen Versionen liegen die Welten. Um welche Versionsnummern geht es?

**Comment by Gerrni** [comment]
ioBroker Admin 3.5.1
Material UI: 0.9.11

Material UpDate zu 0.9.12 müsste ich einer ruhigen Minute machen, bisher ist kein UpDate so richtig sauber gelaufen bzw. benötigt sehr viel Zeit. 

Brauchst Du sonst noch Infos?

**Comment by GermanBluefox** [comment]
Ich glaube dir nicht. Auf der Cloud ist uhralte Version und lokal kann schon 0.9.12/11 sein.

Screenshot?

**Comment by Gerrni** [comment]
Was genau glaubst Du mir nicht? "Wohnzimmer" wird komischerweise nun auch am Smartphone angezeigt. Und bzgl. Pro und Geräte die angezeigt werden lokal aber nicht, siehe Screenshots.... Sowohl bei Garten als auch bei Wohnzimmer.

![screenshot_20180821-064008_chrome](https://user-images.githubusercontent.com/40135870/44383632-a2450d80-a519-11e8-95c9-3279adec4638.jpg)

![screenshot_20180821-064016_chrome](https://user-images.githubusercontent.com/40135870/44383633-a2450d80-a519-11e8-9e8b-eebd9f6cc340.jpg)

![screenshot_20180821-064020_chrome](https://user-images.githubusercontent.com/40135870/44383635-a2dda400-a519-11e8-9215-d5e6fb10bbb0.jpg)

![screenshot_20180821-064037_chrome](https://user-images.githubusercontent.com/40135870/44383636-a2dda400-a519-11e8-9bc4-7a825cffc794.jpg)

![iobrokerpro](https://user-images.githubusercontent.com/40135870/44383397-e7b50b00-a518-11e8-801e-117e0b237a03.png)

![screenshot_20180821-064037_chrome](https://user-images.githubusercontent.com/40135870/44383458-1a5f0380-a519-11e8-822c-f16f4da2f0a4.jpg)

Gruß

**Comment by Gerrni** [comment]
Material 9.1.12 und Admin 3.5.3 soeben installiert. Local noch immer weniger Geräte als per Zugriff auf Material UI über ioBroker.PRO. Vielleicht haben es ja noch andere ansonsten helfe ich gern wo ich kann. 
Oder glaubst noch immer nicht?

**Comment by GermanBluefox** [comment]
Ich glaube immer noch nicht.
Es sind 2 sehr unterschiedliche Versionen auf dem Cloudserver und lokal.
Und man darf die nicht vergleichen

Gerrni <notifications@github.com> schrieb am Di., 21. Aug. 2018, 21:11:

**Comment by Gerrni** [comment]
Du siehst doch das Ergebnis. Anbei nochmal zwei Screenshots. IoBroker pro Material UI  zeigt bei mir Geräte die Material UI lokal nicht anzeigt. 
![screenshot_20180822-063452_chrome](https://user-images.githubusercontent.com/40135870/44443043-eac20100-a5d5-11e8-9f3c-d2998d9fd715.jpg)
![screenshot_20180822-063516_chrome](https://user-images.githubusercontent.com/40135870/44443044-eac20100-a5d5-11e8-9712-a7b754951c84.jpg)

**Comment by Ilovegym66** [comment]
Also wenn ich über die Free Cloud gehe, bekomme ich auch keine Objekte im Material Adapter angezeigt. Ist anscheinend noch eine alte Version installiert, da funktioniert das Editieren noch nicht mal.
HabPanel geht allerdings auch nicht. VIS schon.

**Comment by sigi2345** [comment]
[https://forum.iobroker.net/viewtopic.php?f=30&t=16348#p171438](url)

**Comment by Ilovegym66** [comment]
Das Problem ist wohl einfach, dass man zwar lokal die Version sieht, aber nicht über die Cloud.
Wenn ich das richtig verstehe, sind in der Cloud nur die release Versionen drin, und deshalb geht es nicht, das ist verständlich. 
Ansonsten erstmal ein dickes Lob!! Ich weiß, was du in den letzten Monaten gemacht hast.. :-)

**Comment by Gerrni** [comment]
Material ist auch sehr geil! Aber, Bluefox, verstehst Du nicht, dass ich nicht verstehe warum (Deiner Angabe nach) in der Cloud in einer älteren Version Geräte angezeigt werden, die mir local in einer (Deiner Angabe nach) neueren Version nicht angezeigt werden? Ist doch nicht so schwer und geht auch nicht gegen Dich oder sonstwas. Vielleicht liegt es auch an meinem System aber woran bitte soll es liegen? Außer Adapter installieren kann man ja nicht einstellen.

**Comment by GermanBluefox** [comment]
> Vielleicht liegt es auch an meinem System aber woran bitte soll es liegen?

Weil ich alle Controls neu geschrieben habe und noch nicht alle angepasst sind.

**Comment by Gerrni** [comment]
Ich geb es auf. Danke für die Infos. Ich warte einfach ab und gucke was kommt.

**Comment by GermanBluefox** [comment]
Kannst du channel oder objekt für Lampe 3 
![image](https://user-images.githubusercontent.com/4582016/44919379-ac4ae580-ad3d-11e8-8b37-f2fa814f05f3.png)
hier posten?
Auch welche Kategorien das hat?

**Comment by Gerrni** [comment]
Was genau meinst du? Hilft der Anhang?
![screenshot_20180831-204354_chrome](https://user-images.githubusercontent.com/40135870/44930554-fee8c980-ad5e-11e8-842e-86e560312b41.jpg)


Was mir aufgefallen ist, eigentlich heißt die Garten Lampe 3, Material über iobroker pro zeigt Lampe 3 an.

**Comment by GermanBluefox** [comment]
Einfach zum Testen: kannst du Device Garten Lampe 3 auf Channel ändern?

Gerrni <notifications@github.com> schrieb am Fr., 31. Aug. 2018, 20:47:

**Comment by Gerrni** [comment]
Anstelle "device" hab ich nun "channel" gesetzt. Material lokal zeigt die Lampen im Garten jedoch noch immer nicht an. Die sind per Deconz Adapter eingebunden. Iobroker.pro zeigt sie Wie schon zuvor alle an.

**Comment by GermanBluefox** [comment]
Kannst du hier dein tree importieren? Dann werde ich versuchen zu
reproduzieren

сб, 1 сент. 2018 г., 19:55 Gerrni <notifications@github.com>:

**Comment by Gerrni** [comment]
Wovon genau, meinst du alle Objekte von Lampe 3?

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.material/issues/17#issuecomment-415196709

**Comment by Gerrni** [comment]
Ach so. Die Datei kann ich hier aber nicht importieren.

**Comment by GermanBluefox** [comment]
> Ach so. Die Datei kann ich hier aber nicht importieren.
info at iobroker.net

**Comment by GermanBluefox** [comment]
Kannst du an email senden?

**Comment by Gerrni** [comment]
Hast Mail bekommen, am 08. Geschickt. Mit aktueller Version besteht das Problem noch immer und Material ist zumindest für mich nicht nutzbar. Kann mir eigentlich nicht vorstellen das ist der einzige bin der deconz nutzt und das Problem hat. Kann ich noch irgendwie helfen?

**Comment by Gerrni** [comment]
Gibt es hier schon News die ich übersehen habe?
