### ISSUE TITLE
Geräte/Variablen anordnen

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.material#16]
Ich versuche derzeit Geräte/Variablen anders anzuordnen, jedoch wird meine Anordnung nicht gespeichert. Die Geräte/Variablen werden alphabetisch sortiert.

**Comment by dontobi** [comment]
Hier ein ![Screenshot](https://www.dropbox.com/s/kg6lrolz2skestd/Screenshot_20180820-162715.jpg?dl=0&m=)

**Comment by GermanBluefox** [comment]
Screenshot von Einordnung?

**Comment by GermanBluefox** [comment]
Kein Bild.

Tobias S. <notifications@github.com> schrieb am Mo., 20. Aug. 2018, 16:30:

**Comment by dontobi** [comment]
Ich hab das Bild verlinkt. Clicke Mal auf "Screenshot".

**Comment by GermanBluefox** [comment]
Non-Image content-type returned


вт, 21 авг. 2018 г., 8:06 Tobias S. <notifications@github.com>:

**Comment by dontobi** [comment]
https://www.dropbox.com/s/kg6lrolz2skestd/Screenshot_20180820-162715.jpg?dl=0&amp;m=

**Comment by dontobi** [comment]
Ja, es gibt aber noch einen Button "Schlafzimmer Rollläden zu" (Variable: Schlafen). Das wollte ich unter einander anordnen, aber nachdem ich das angepasst habe und aus dem Einstellungsmodus raus gehe, ist alles wieder alphabetisch sortiert.
