### ISSUE TITLE
Support Wifilight

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.material#17]
Hi,
add support for Wifilight Adapter, please.
I've added all Wifilights, but no one are displayed. ( and not hidden, nothing.. )

**Comment by GermanBluefox** [comment]
Please export here the structure of one device. 
![image](https://user-images.githubusercontent.com/4582016/44493400-20afc580-a668-11e8-99df-c9dd9324d6a6.png)

**Comment by Ilovegym66** [comment]
Hi,
attached the export as .json

[wifilight.0.192_168_178_111.json.zip](https://github.com/ioBroker/ioBroker.material/files/2313317/wifilight.0.192_168_178_111.json.zip)

**Comment by GermanBluefox** [comment]
No go.. All states have wrong roles. The wifilight adapter must be fixed first

**Comment by Apollon77** [comment]
Open an issue with the adapter. The developer should fix that.

**Comment by Ilovegym66** [comment]
@Apollon77 
looks like you're the last developer of the wifilight Adapter..?? :-)

**Comment by Apollon77** [comment]
Sorry, nope ...
