### ISSUE TITLE
Unterschied bei der Zuweisung..

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.material#18]
Hi, Version 0.9.12 und Admin 3.5.5
habe gerade festgestellt, dass irgendwas sich beisst, mir wurden Objekte angezeigt, nachdem ich diese per Räume/Funktionen zugewiesen hatte.
Habe anschliessend eine Änderung gemacht über die Funktion Objekte/Räume/Funktionen ( das ja jetzt einfach per Klick zu machen ist), und jetzt werden diese Objekte in Material gar nicht mehr angezeigt.

Irgendwas sync da nicht.. ?

**Comment by GermanBluefox** [comment]
Damit kann ich wirklich schlecht anfangen.

Bitte die Objekte "enum.rooms.*" enum.functions.* anschauen.

**Comment by Ilovegym66** [comment]
closed, fixed with 0.10.5.
