### ISSUE TITLE
Feature Add Function/Room Icon for default

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.material#19]
Beispiel:
habe für die Funktionen und Räume eigene Icons gesetzt.
Jetzt füge ich ein Gerät einer Funktion oder einem Raum neu hinzu, kann der Adapter da nicht automisch das gesetzte Icon für das Gerät benutzen?

So muss man nach dem Hinzufügen immer erst wieder das Gerät aufrufen und Stück für Stück die Icons ändern. Sozusagen ein "Parent"-Icon :-) .. .oder Einstellbar, im Mobile Adapter gibts die Funktion, dass man das Gerät-Eigene Icon oder ein Standard benutzen kann...

**Comment by GermanBluefox** [comment]
Aktuell man konnte default Icon auswählen. Please test.

**Comment by Ilovegym66** [comment]
Ja, funktioniert, zumindest bei den Xiaomi, wie im anderen Issue.

**Comment by GermanBluefox** [comment]
>wie im anderen Issue.

Was meinst du?

**Comment by Ilovegym66** [comment]
ich meine, die Xiaomi Devices bringen ja eigene Icons mit, diese kann ich setzen, es werden aber bei den Doorcontacts, Switch und Cube nur das Batterie-Icon als default angezeigt und gesetzt. ( dies ist ja im rechten Feld, im linken wird kein icon angezeigt. ) 
Beim Gateway funktioniert es wunderbar, im linken Feld(oder Knopf wo ich das Licht anschalten kann) sieht man das Icon vom Gateway, im rechten dann für Lautstärke, Helligkeit usw. das ist ok.

Was ich oben aber meinte, ist, wenn ich im IOBROKER bei FUNKTION das Icon ändere, zum Beispiel habe ich eine schöne farbige Lampe als Icon, dann sollte man das für die Lampen, die ich zuordne, übernehmen können.

**Comment by GermanBluefox** [comment]
Wieso änderst du bei FUNKTION und nicht beim Objekt?

**Comment by GermanBluefox** [comment]
Ich verstehe immer noch nicht.

**Comment by GermanBluefox** [comment]
Please test 0.10.5
