### ISSUE TITLE
Support Xiaomi

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.material#20]
Hi,
habe mal von den verschiedensten Xiaomi Devices n Export gemacht, bei dem Temp-Anzeigen gibts n Text-Overlap im zweiten Icon, wo Batterie% und Luftfeuchte, Batteriespannung angezeigt wird.
( Screenshot kommt noch )
Hier erstmal alles von Xiaomi, was ich so habe.. Cube, Taster, Sensor mit und ohne Luftfeuchte, Magnete, Motion Sensor, Gateways, unter ble.xxx findest du die Flora Bluetooth, wäre schön, wenn das richtig angezeigt würde. :-)
[xiaomi.zip](https://github.com/ioBroker/ioBroker.material/files/2313366/xiaomi.zip)

**Comment by Ilovegym66** [comment]
Screenshots:
![bildschirmfoto vom 2018-08-23 09-34-48](https://user-images.githubusercontent.com/36229898/44511446-e0783380-a6b7-11e8-95a9-16f760d9f114.png)
![bildschirmfoto vom 2018-08-23 09-33-29](https://user-images.githubusercontent.com/36229898/44511447-e0783380-a6b7-11e8-9a0f-091a5758361a.png)
![bildschirmfoto vom 2018-08-23 09-33-04](https://user-images.githubusercontent.com/36229898/44511448-e0783380-a6b7-11e8-8e68-181e5b6a8be6.png)

**Comment by Ilovegym66** [comment]
..da kam gerade einer ( Roborock S50) und saugte unterm Stuhl durch... auch hiervon die .json
:-)
[xiaomivacuum.zip](https://github.com/ioBroker/ioBroker.material/files/2313400/xiaomivacuum.zip)

**Comment by GermanBluefox** [comment]
How would you suggest to solve this problem?
![image](https://user-images.githubusercontent.com/4582016/44918906-6b060600-ad3c-11e8-9d93-121515741b1e.png)
Just to cut the voltage?

**Comment by Ilovegym66** [comment]
yes, cut it and take the voltage in the overview ( the page popped up if I click the right upper corner on the icon). Important is the battery level in %.

**Comment by GermanBluefox** [comment]
Should be fixed in 0.10.5. Please test

**Comment by Ilovegym66** [comment]
yes, it's fixed! thank you very much! Great!
