### ISSUE TITLE
yeelight ct only

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.material#23]
hi bluefox first of all thanks, ct works great in combination with rgb. i also have  "normal" bulbs with dimm and change ct 
![2018-09-10_19h20_35](https://user-images.githubusercontent.com/6328382/45313391-15e1a580-b52f-11e8-9d28-1226f86fcca5.png)

[yeelight-2.0.txt](https://github.com/ioBroker/ioBroker.material/files/2367695/yeelight-2.0.txt)

**Comment by GermanBluefox** [comment]
Should be fixed in 0.10.5. Please test

**Comment by MeisterTR** [comment]
works perfect, thanks
