### ISSUE TITLE
Bei Anwahl Kachel zur Einstellung RGB wird die Seite weiß

### ISSUE THREAD

**Issue by LausiD** [ioBroker/ioBroker.material#27]
Tritt nur auf wenn Role "light.color.rgb" und keine Role "light.color.temperature" vergeben wurde.
Gruß LausiD

**Comment by LausiD** [comment]
![grafik](https://user-images.githubusercontent.com/38705515/45828510-fe59a800-bcf8-11e8-80da-e534f7e3919d.png)

**Comment by GermanBluefox** [comment]
Should be fixed in 0.10.5. Please test
