### ISSUE TITLE
Feature: zweite Instanz oder Profil?

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.material#28]
Ist es machbar, eine zweite Instanz/Profil anzulegen, damit man für z.bsp. Mitbewohner eine kurze Übersichtsseite machen kann? Kann ja auf der gleichen Grundlage der enums.xx basieren, nur mit anderen Ein/Ausblendungen.. 
Soweit ich das sehe, wird die eigentlich "config" ja im Raw des jeweiligen Objects abgespeichert, hier bräuchte man ja dann nur zusätzliche Einträge machen.. oder??
Oder die Benutzerverwaltung mit Auth ? Wenn ich das einschalte und NICHT als admin eingeloggt bin, bekomme ich nur eine weiße Seite angezeigt, anscheinend keine Rechte.. obwohl in der gleichen Gruppe (Admin).

**Comment by Apollon77** [comment]
Zweite Instanz und anders konfigurieren?

**Comment by Ilovegym66** [comment]
Genau, z.bsp. ne Übersicht mit allen devices, wo alles eingeblendet ist, und eine, bei der einige ausgeblendet sind.

**Comment by GermanBluefox** [comment]
Das geht über User. Bitte einen zwriten Anwender erzeugen und entwieder
authentifizierung einschalteten oder zweite web instanz installieren und
"Run as" definieren

вс, 16 сент. 2018 г., 20:50 Ilovegym66 <notifications@github.com>:

**Comment by Ilovegym66** [comment]
Das ist theoretisch Klasse, und genau das, was ich brauche, funktioniert aber aktuell nicht. :-(
Mit Habpanel geht es, mit Vis auch, nur Material bleibt bei "lade objekte"stehen und macht nix mehr.

**Comment by GermanBluefox** [comment]
Dann hast du bug gefunden.

**Comment by GermanBluefox** [comment]
> Das ist theoretisch Klasse, und genau das, was ich brauche, funktioniert aber aktuell nicht. :-(
> Mit Habpanel geht es, mit Vis auch, nur Material bleibt bei "lade objekte"stehen und macht nix mehr.

Dann sollte da was in der Browser Konsole stehen.

**Comment by Ilovegym66** [comment]
in der Browser Konsole steht ja recht viel.. schau mal, vielleicht kannst du was mit anfangen, der Benutzer hat auch Admin-Rechte, mit Habpanel kann ich eine neue View machen, bei Material 0.10.4 bleibt er bei "objekte lesen" stehen:
`Invalid chrome URI: /
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. index.html
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: call to eval() or related function blocked by CSP. vendor.js:189
Attempt to set a forbidden header was denied: Connection
1022738457-lcs_client_bin.js:195:386
Attempt to set a forbidden header was denied: Connection
[Show/hide message details.] TypeError: n.appConfig is undefined
main.6db86ca9.js:1:465277
Unsibscribe: system.host.* app.js:1:293135
Unsibscribe: system.adapter.* app.js:1:293135
Unsibscribe: *.info.connection app.js:1:293135
Invalid chrome URI: /
Subscribe: system.adapter.* app.js:1:292720
Subscribe: system.host.* app.js:1:292720
Subscribe: *.info.connection app.js:1:292720
Invalid chrome URI: /
108 app.js:1:189138
Size of stored data: 0k. Max possible: 5000k main.6db86ca9.js:1:467341
Error during service worker registration: <unavailable> main.6db86ca9.js:1:1330045
2018-10-16T08:32:40.946Z Connected => authenticate vendor.js:1:4606
2018-10-16T08:32:41.072Z Authenticated: true vendor.js:1:4908
[Show/hide message details.] TypeError: n.appConfig is undefined main.6db86ca9.js:1:465277
Attempt to set a forbidden header was denied: Connection 1022738457-lcs_client_bin.js:195:386`

**Comment by Ilovegym66** [comment]
siehe auch 
https://github.com/ioBroker/ioBroker.web/issues/14
wusste nicht, wohin mit dem Bug.. :-) betrifft ja auch Habpanel, da "merkt" er sich nichts. Denke daher der Fehler liegt irgendwo in der Benutzerverwaltung/-rechten..?

**Comment by GermanBluefox** [comment]
Should be fixed in 0.10.5. Please test

**Comment by Ilovegym66** [comment]
funktioniert! Vielen Dank, das ist super wie der Adapter jetzt läuft!
