### ISSUE TITLE
White screen on settings (v 0.10.4)

### ISSUE THREAD

**Issue by csplkiller** [ioBroker/ioBroker.material#29]
I get a white screen when I click the Settings button. I can not do anything about it.

![2018-09-17_23-08-33](https://user-images.githubusercontent.com/7470513/45647511-b7886a00-bace-11e8-9257-4d204dfcfa6f.png)

![2018-09-17_23-09-50](https://user-images.githubusercontent.com/7470513/45647618-fb7b6f00-bace-11e8-9d4a-0c635110c56e.png)

![2018-09-17_23-10-08](https://user-images.githubusercontent.com/7470513/45647558-d7b82900-bace-11e8-896f-6e6710b01474.png)

**Comment by csplkiller** [comment]
Install instruction:

> npm i gulp-cli -g
> cd /opt/iobroker
> npm i https://github.com/ioBroker/ioBroker.material/tarball/master
> cd /opt/iobroker/node_modules/iobroker.material
> npm i
> gulp

`
root@smarthome:/opt/iobroker/node_modules/iobroker.material# cd /opt/iobroker
root@smarthome:/opt/iobroker# npm i https://github.com/ioBroker/ioBroker.material/tarball/master
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bgblack/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bgblue/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bgcyan/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bggreen/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bgmagenta/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bgred/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bgwhite/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bgyellow/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-black/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-blue/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-bold/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-cyan/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-dim/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-gray/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-green/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-grey/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-hidden/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-inverse/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-italic/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-magenta/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-red/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-reset/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-strikethrough/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-underline/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-white/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-wrap/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/ansi-yellow/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/aproba/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/arr-flatten/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/choices-separator/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/clone-deep/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/commander/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/deep-extend/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/detect-libc/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/github-from-package/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/is-accessor-descriptor/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/is-data-descriptor/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/is-descriptor/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/mixin-object/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/mute-stream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/noop-logger/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/object-copy/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/promirepl/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/prompt-actions/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/prompt-base/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/prompt-checkbox/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/prompt-choices/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/prompt-question/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/prompt-radio/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/readline-ui/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/serialport/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/shallow-clone/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/simple-concat/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/static-extend/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/terminal-paginator/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/object-copy/node_modules/is-descriptor/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/static-extend/node_modules/is-accessor-descriptor/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/static-extend/node_modules/is-data-descriptor/package.json'
npm WARN react-beautiful-dnd@9.0.2 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion@0.5.2 requires a peer of react@^0.14.9 || ^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux@5.0.7 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

+ iobroker.material@0.10.4
removed 481 packages, updated 1 package and audited 2458 packages in 158.989s
found 57 vulnerabilities (39 low, 2 moderate, 16 high)
  run `npm audit fix` to fix them, or `npm audit` for details
`

**Comment by JoJ123** [comment]
I have the same, when I open the settings (on the element the right corner) of my hue lights in some rooms

**Comment by GermanBluefox** [comment]
>I have the same, when I open the settings (on the element the right corner) of my hue lights in some rooms

Same error message in the console too?

**Comment by JoJ123** [comment]
Oh I didn't saw that, no for me it's *id* instead of *noCache* Sry.

**Comment by GermanBluefox** [comment]
>Oh I didn't saw that, no for me it's id instead of noCache Sry.

How does the error look exactly ? Screenshot?

**Comment by JoJ123** [comment]
Ich habe in den Objekten allen Hue Ordner die Lampen aus der "Küche" enthalten einen Raum und Funktion zugeordnet, also dem Channel nicht einzelnen States

Error, wenn ich bei dem Widget auf die kleine umgeklappte Ecke klicke:
![image](https://user-images.githubusercontent.com/38938791/46966067-e7666580-d0ac-11e8-80ec-f5ea696ad078.png)

Das zeigt er alles an:
![image](https://user-images.githubusercontent.com/38938791/46966142-28f71080-d0ad-11e8-8a9c-401989b723d1.png)

Json:
[hue.0.Philips_hue.zip](https://github.com/ioBroker/ioBroker.material/files/2479851/hue.0.Philips_hue.zip)

**Comment by JoJ123** [comment]
I have "old" hue lights in my system, maybe this is the problem?

**Comment by GermanBluefox** [comment]
Das ist komplett ein anderes Problem, aber das habe ich auch gefixt. Release folgt

**Comment by JoJ123** [comment]
Nice! Thanks a lot!

**Comment by GermanBluefox** [comment]
Should be fixed in 0.10.5. Please test

**Comment by Ilovegym66** [comment]
is fixed, 0.10.5 is a very good version!

**Comment by GermanBluefox** [comment]
@csplkiller @JoJ123 Fixed?

**Comment by JoJ123** [comment]
Hi checked right now and it's fixed! Thanks!
But I'm still a bit confused, which states from hue I should set to rooms and function (light)

I have so many widgets in material for the hue, I put the channel of each light and "hue room" to a material room and function. Is that right?

**Comment by GermanBluefox** [comment]
> Hi checked right now and it's fixed! Thanks!
> But I'm still a bit confused, which states from hue I should set to rooms and function (light)
> 
> I have so many widgets in material for the hue, I put the channel of each light and "hue room" to a material room and function. Is that right?

Not the states. Whole channels and devices.
