### ISSUE TITLE
Rolle level.volume wird nicht erkannt

### ISSUE THREAD

**Issue by LausiD** [ioBroker/ioBroker.material#30]
Anlage state Volume durcn FHEM Adapter wird nicht erkannt.
"fhem.0.sonos_WZ_PLAYBAR.Volume": {
"_id": "fhem.0.sonos_WZ_PLAYBAR.Volume",
"type": "state",
"common": {
"name": "sonos_WZ_PLAYBAR Volume",
"role": "level.volume",
"type": "number",
"min": "0",
"max": "100",
"unit": "%",
"write": true,
"read": true
},
"native": {
"Name": "sonos_WZ_PLAYBAR",
"Attribute": "Volume",
"possibleSets": true,
"volume": true,
"ts": 1537297134012,
"Readings": true
},
"from": "system.adapter.fhem.0",
"user": "system.user.admin",
"ts": 1537297181506,
"acl": {
"object": 1636,
"state": 1636,
"owner": "system.user.admin",
"ownerGroup": "system.group.administrator"
}

Objekt bearbeiten, speichern und wird erkannt
"fhem.0.sonos_WZ_PLAYBAR.Volume": {
"from": "system.adapter.fhem.0",
"user": "system.user.admin",
"ts": 1537297181506,
"common": {
"name": "sonos_WZ_PLAYBAR Volume",
"role": "level.volume",
"type": "number",
"min": 0,
"max": 100,
"unit": "%",
"write": true,
"read": true
},
"native": {
"Name": "sonos_WZ_PLAYBAR",
"Attribute": "Volume",
"ts": 1537297134012,
"possibleSets": true,
"volume": true,
"Readings": true
},
"acl": {
"object": 1636,
"owner": "system.user.admin",
"ownerGroup": "system.group.administrator",
"state": 1636
},
"_id": "fhem.0.sonos_WZ_PLAYBAR.Volume",
"type": "state"
}

https://forum.iobroker.net/viewtopic.php?f=8&t=16983

**Comment by GermanBluefox** [comment]
Bitte Issue an fhem schreiben, dass min und max als string definiert sind.

**Comment by LausiD** [comment]
Vielen Dank bluefox
Ist jetzt  im FHEM Adapter geändert
