### ISSUE TITLE
Rooms/enums not correctly syncronised/visible within Material Ui

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.material#31]
i create 2 rooms in CCU and ensured these rooms and related devices are visible in iObroker.
Unfortunalty the new room is not visible in MaterialUi, and previous deleted room is still visible and not the new room and related devices. See screenshots below:

![image](https://user-images.githubusercontent.com/7318445/45805850-eade1b00-bcbf-11e8-8c1f-76166aabec91.png)

![image](https://user-images.githubusercontent.com/7318445/45805867-f4678300-bcbf-11e8-8107-70170975ac07.png)

developer console output (chrome):

![image](https://user-images.githubusercontent.com/7318445/45805905-09441680-bcc0-11e8-9f8f-a15895a456dd.png)

**Comment by DutchmanNL** [comment]
After deletion of the instance, the adapter itself and a complete reinstallation all enums are not shown as expected.

If someone runs into these troubles please execute on console:

`sudo iobroker del material
sudo iobroker add material`

**Comment by GermanBluefox** [comment]
are not shown  => are now shown ?

**Comment by DutchmanNL** [comment]
Shown, sorry ;)
