### ISSUE TITLE
Zuordnung wenn mehrere Räume oder Funktionen vergeben sind

### ISSUE THREAD

**Issue by Stormbringer11** [ioBroker/ioBroker.material#33]
Zuordnung wenn mehrere Räume oder Funktionen vergeben sind funktioniert leider nicht.

**Comment by Stormbringer11** [comment]
Also wenn ein Datenpunkt mehr wie ein Raum oder Funktion zugeordnet ist. Wird dieser nicht bei allen Räumen und Funktionen angezeigt

**Comment by Ilovegym66** [comment]
Hier auch nachvollziehbar, allerdings habe ich nur Geräte, denen zwei Funktionen ( Fenster, Sicherheit) zugeordnet sind.
@Stormbringer11  Geräte, die gleichzeitig in zwei Räumen sind, habe ich nicht.. :-) erinnert mich irgendwie an Schrödingers Katze ..:-)
