### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Tagiwara** [ioBroker/ioBroker.material#34]
Nach der Installation des Material UI Adapters möchte ich den gerne aufrufen. Ich erhalte dann folgende Fehlermeldung: File 0.10.4/index.html not found: Not exists

In die Config des Adapters komme ich auch nicht.

**Comment by Apollon77** [comment]
iobroker upload material
 Ausgeführt?

Installiert aus latest repo und nicht vom GitHub?

Forum gesucht, da ist das schon zu finden.

**Comment by Tagiwara** [comment]
iobroker upload material habe ich ausgeführt. Installiert direkt aus IoBroker von der latest repo

**Comment by Tagiwara** [comment]
Nein, via npm installiert. mehrfach jetzt schon deinstalliert und neu aufgespielt. kein Erfolg.

Ich kann aber auch nirgends eine Lösung finden.

**Comment by Ilovegym66** [comment]
hast du https aktiviert? funktionieren andere Seiten? Habpanel, Mobile ?
Socket.io Adapter installiert? Konfig? 
Bei mir halb ein downgrade auf 0.9.x, Seite Material aufrufen, Objekte einlesen lassen, Seite schliessen.
Dann update des Adapter auf 0.10.4 und funktioniert.

**Comment by Tagiwara** [comment]
Was für ein strunz. Ist schon wieder runter geflogen. Hab ich keine Zeit zu stundenlang zu rüffeln um den Adapter ans laufen zu bekommen.

**Comment by Apollon77** [comment]
Sehr Schade das Du für die Community nicht bereit bist bei der Fehlersucht und Eingrenzung zu unterstützen. 
Und am Ende heissts wieder irgendwo "iobroker ist blöd weil tut ja nicht" :-(

**Comment by Tagiwara** [comment]
Doch bin ich grundsätzlichschon und IoBroker liebe ich. Aber dieser Adapter läuft halt nicht und eine Lösung finde ich nicht. Auch hier finde ich keine Lösung.

Beiträge wie "Socket.io Adapter installiert" oder "Konfig?" oder "Habpanel, Mobile" bringen rein gar nix. Da sollte man schon dabei schreiben was man denn damit meint. 

und das ich aus der latest repo installiert habe, hatte ich oben schon geschrieben, da muss man ja nicht nochmal und nochmal nachfragen.

Aber alles gut: Ist halt ein Adapter der nicht läuft und auch kein Beinbruch (für mich zumindest)

**Comment by Ilovegym66** [comment]
@Tagiwara um helfen zu können, braucht man einfach mehr Informationen, wenn Du diese nicht lieferst, kann unsere Glaskugel einfach keine Analyse machen.. 
Gerade der Material-Adapter arbeitet eben mit Sockets und dem Webadapter und dessen Konfig zusammen, wie soll man helfen, wenn man nicht mal weiß, was du installiert und eingestellt hast?
Okay, vielleicht war meine Fragestellung etwas zu knapp und nicht ausführlich genug, sorry.

Auf der anderen Seite kann ich Dich auch verstehen, wenn du nicht soviel Zeit in die Fehlersuche investieren magst/kannst (man hat ja auch noch anderes im Leben vor..).

Ich würde solange daran arbeiten, bis ich wenigstens wüsste, warum es nicht funktioniert :-) :-)

**Comment by Tagiwara** [comment]
Also nochmal langsam :-)
Ich habe den Adapter entsprechend der Anleitung hier auf Github installiert. In der Installationsanleitung (sofern man das nichtssagende readme so beschreiben kann) steht leider nichts von sockets und webadaptern.

Und als Information kann ich halt nur liefern:
- nein ich habe nicht von Github installiert sondern über npm
und
- ich erhalte nach erfolgreicher Installation beim Aufruf die Fehlermeldung "File 0.10.4/index.html not found: Not exists"

Dann wurde ich gefragt, ob ich den Befehl "iobroker upload material" abgesetzt habe. Auch hierzu findet sich in der Installationsanleitung kein Hinweis...rausgefunden habe ich das durch meine Suche im IoBroker Forum. Also habe ich den Befehl abgesetzt. Das Ergebnis blieb aber das gleiche.

Dann bekomme ich hier den Beitrag: hast du https aktiviert? **WO?** funktionieren andere Seiten? **Was ist mit anderen Seiten gemeint?**Habpanel, Mobile ? **Was ist das, wozu braucht man das?**
Socket.io Adapter installiert? **Nein, warum auch? Steht ja nirgendwo das das gemacht werden muss.** Konfig? **Was bedeutet das? Meine IoBroker Konfig? Adapter Konfig? Wonach wurde gefragt?**
Bei mir halb ein downgrade auf 0.9.x, Seite Material aufrufen, Objekte einlesen lassen, Seite schliessen.
Dann update des Adapter auf 0.10.4 und funktioniert. **Wo bekomme ich denn die "alte" Version her? Anscheinend scheint es ja ein Problem zu geben mit dem Adapter sonst wäre ein downgrade ja nicht notwendig**
(die fetten Teile habe ich jetzt gerade eingefügt um klar zu machen das ich das nicht verstanden habe)

Ich würde sehr gerne mehr Informationen liefern, wenn man mir denn die korrekten Fragen stellen würde.
Und oben habe ich geschrieben, dass ich nicht in die Konfig des Adapters reinkomme. Somit kann ich da auch nix eingestellt haben.

**Comment by Tagiwara** [comment]
Ok, danke dir für deine Geduld :-) Vielleicht sollte der Entwickler seine readme einmal anpassen und ein paar mehr Informationen preis geben.

Ich werde die Zeit die ich bräuchte um den Material Adapter ans laufen zu bekommen, lieber in die VIS stecken. Gedacht war es andersherum, da mir die VIS zu Zeitintensiv war.

**Comment by GermanBluefox** [comment]
Deine web adapter version?

**Comment by GermanBluefox** [comment]
You need at least 2.4.1
https://github.com/ioBroker/ioBroker.web/blob/master/README.md#241-2018-07-21

**Comment by Apollon77** [comment]
Sollte das dann nicht als dep in io-package bei material definiert sein?

**Comment by GermanBluefox** [comment]
>Sollte das dann nicht als dep in io-package bei material definiert sein?

https://github.com/ioBroker/ioBroker.material/blob/master/io-package.json#L204

Keine Ahnung, wie er das installiert hat.

**Comment by Apollon77** [comment]
hm ... :(

**Comment by Apollon77** [comment]
Na dann close hier ...

**Comment by Tagiwara** [comment]
Wow, geschlossen? Läuft bei euch.

**Comment by Apollon77** [comment]
Du kannst es gern reopen wenn es mit web >=2.4.1 immer noch nicht tut!
