### ISSUE TITLE
Media Player Bose Soundtouch

### ISSUE THREAD

**Issue by JoJ123** [ioBroker/ioBroker.material#35]
For the Media Player Implementation in Material UI:

I need to make most of the media states available?
https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md

Is there a demo how the media player will look?

I added one field which is displaying the volume to a room, to the function "Audio" and change role to level.volume, but I just get a "field" in Material UI where I can type the volume in an input field.

I would love to include this in the Bose Soundtouch Adapter.

**Comment by GermanBluefox** [comment]
Not all states. Only states from here
https://github.com/ioBroker/ioBroker.type-detector/blob/master/index.js#L98
with a flag required:true. And just now it is only one boolean state with
role media.state

пн, 15 окт. 2018 г. в 14:08, Johannes Jaeger <notifications@github.com>:

**Comment by JoJ123** [comment]
But will it display a "special" Media Player?
I tried it with COVER or TITLE, but in both it just end up in two new widget with the value of the state, not an Player, Image or something like this...
Do I have to add more the role and name?

Result:
![image](https://user-images.githubusercontent.com/38938791/46970478-7c6f5b80-d0b9-11e8-94dd-ec069c6a4d08.png)

JSON of speaker:
[bosesoundtouch.2.zip](https://github.com/ioBroker/ioBroker.material/files/2480033/bosesoundtouch.2.zip)

**Comment by GermanBluefox** [comment]
Do you have this one?
https://github.com/ioBroker/ioBroker.type-detector/blob/master/index.js#L98

**Comment by JoJ123** [comment]
I forgot the set name="STATE", but also after setting this it's not working:
![image](https://user-images.githubusercontent.com/38938791/46977745-3fad5f80-d0cd-11e8-8747-5d6db8080f70.png)

**Comment by Apollon77** [comment]
Äähm isd "on" state really a indicator if playing or pause? media.state should be "true" when something is playing and false if not. on is more a "power=on" state or ?!

**Comment by JoJ123** [comment]
Sure it's not the best one for this, but it's a Boolean.
I just want to see how it will work, then I will create the states in the code of the adapter.

**Comment by JoJ123** [comment]
Just to ask again, what should I see, when I have the following states:
`id: 'on', role: media.state, type: 'boolean', name: 'STATE'`
`id: 'volume', role: level.volume, type: 'number', name: 'VOLUME', min:0, max: 100`

What does these fields mean: 
`required: false, notSingle: true, noSubscribe: true`

What this field is for, do I have to add it somewhere?
`type: Types.media`

**Comment by GermanBluefox** [comment]
> Just to ask again, what should I see, when I have the following states:
> `id: 'on', role: media.state, type: 'boolean', name: 'STATE'`
> `id: 'volume', role: level.volume, type: 'number', name: 'VOLUME', min:0, max: 100`
> 
> What does these fields mean:
> `required: false, notSingle: true, noSubscribe: true`
> 
> What this field is for, do I have to add it somewhere?
> `type: Types.media`

you can find the description of specific attributes here: https://github.com/ioBroker/ioBroker.type-detector/blob/master/index.js#L65

But it is the description for type-detector and not for states.

>Just to ask again, what should I see, when I have the following states:

You will see one tile in form of media player with 1 button (play/pause) and if you click on tile you will see the additionally to play button the volume slider.
