### ISSUE TITLE
Support Xiaomi Aqara Sensoren 

### ISSUE THREAD

**Issue by southparkler** [ioBroker/ioBroker.material#41]
Es wäre super wenn die Xiaomi Aqara Sensoren (Temperatur, Fenster, Motion,Wasser...etc) unterstützt würden.

Vielen Dank

**Comment by southparkler** [comment]
Da ich noch recht neu im Thema ioBroker bin weiß ich nicht genau wasdu brauchst. Anbei mal ein Screenshot vom Aqara humidity und Aqara motion Sensor.
Den Fenstersensor bekomme ich erst die Tage, Wassersensor hab ich (noch) nicht bestellt.

![objeke_xiaomi_zigbee](https://user-images.githubusercontent.com/45282528/48969506-d855ca00-efff-11e8-9add-49c15308851a.jpg)

**Comment by emddummi** [comment]
Dann klick mal auf den werkzeugschlussel, dann sollte iwo der Punkt raw stehen. Die Daten darunter brauch er

**Comment by southparkler** [comment]
Aqara Motion Sensor
`{
  "from": "system.adapter.zigbee.0",
  "ts": 1543075096566,
  "common": {
    "name": "BewegungTreppe2OGXiaomiAqara1",
    "type": "lumi.sensor_motion.aq2",
    "icon": "img/aqara_numan_body_sensor.png"
  },
  "native": {
    "id": "00158d00029c0723"
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "zigbee.0.00158d00029c0723",
  "type": "device"
}`

Aqara Humidity Sensor

`{
  "type": "device",
  "common": {
    "name": "TemperaturAußenXiaomiAquara",
    "type": "lumi.weather",
    "icon": "img/aqara_temperature_sensor.png"
  },
  "native": {
    "id": "00158d00027732ce"
  },
  "from": "system.adapter.zigbee.0",
  "ts": 1543070150330,
  "_id": "zigbee.0.00158d00027732ce",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Reicht das oder von jedem

**Comment by southparkler** [comment]
Aqara Humidity Sensor (Ordner)

`{
  "type": "device",
  "common": {
    "name": "TemperaturAußenXiaomiAquara",
    "type": "lumi.weather",
    "icon": "img/aqara_temperature_sensor.png"
  },
  "native": {
    "id": "00158d00027732ce"
  },
  "from": "system.adapter.zigbee.0",
  "ts": 1543070150330,
  "_id": "zigbee.0.00158d00027732ce",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Aqara Humidity Sensor Luftfeuchtigkeit

`{
  "type": "state",
  "common": {
    "name": "Battery percent",
    "type": "number",
    "unit": "%",
    "read": true,
    "write": false,
    "role": "battery.percent",
    "min": 0,
    "max": 100,
    "icon": "img/battery_p.png"
  },
  "from": "system.adapter.zigbee.0",
  "ts": 1543081351219,
  "_id": "zigbee.0.00158d00027732ce.battery",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}`

Aqara Humidity Sensor Battery

`{
  "type": "state",
  "common": {
    "name": "Humidity",
    "type": "number",
    "unit": "%",
    "read": true,
    "write": false,
    "role": "value.humidity",
    "min": 0,
    "max": 100
  },
  "from": "system.adapter.zigbee.0",
  "ts": 1543082054895,
  "_id": "zigbee.0.00158d00027732ce.humidity",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}`

Aqara Humidity Sensor Luftdruck

`{
  "type": "state",
  "common": {
    "name": "Pressure",
    "type": "number",
    "unit": "hPa",
    "read": true,
    "write": false,
    "role": "value.pressure",
    "min": 0,
    "max": 100
  },
  "from": "system.adapter.zigbee.0",
  "ts": 1543082054897,
  "_id": "zigbee.0.00158d00027732ce.pressure",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}`

Aqara Humidity Sensor Temperatur

`{
  "type": "state",
  "common": {
    "name": "Temperature",
    "type": "number",
    "unit": "°C",
    "read": true,
    "write": false,
    "role": "value.temperature"
  },
  "from": "system.adapter.zigbee.0",
  "ts": 1543082054884,
  "_id": "zigbee.0.00158d00027732ce.temperature",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}`

Aqara Humidity Battery Volt

`{
  "type": "state",
  "common": {
    "name": "Battery voltage",
    "type": "number",
    "unit": "V",
    "read": true,
    "write": false,
    "role": "battery.voltage",
    "icon": "img/battery_v.png"
  },
  "from": "system.adapter.zigbee.0",
  "ts": 1543081351217,
  "_id": "zigbee.0.00158d00027732ce.voltage",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}`

Hoffe das passt so. Wenn noch was gebraucht wird - einfach schreiben.

**Comment by southparkler** [comment]
Glaub das ist einfacher - ich lerne ;)
[Objekte_json.zip](https://github.com/ioBroker/ioBroker.material/files/2612553/Objekte_json.zip)

**Comment by obiwan007** [comment]
Sind die Xiaomi Sensoren inzwischen irgendwie einbindbar? Hängen bei mir auch an einem Zigbee Adapter.
Gibt es einen Workaround, wie man die sichtbar machen kann?

**Comment by southparkler** [comment]
Also, alle Sensoren gehen von Haus aus. Man muss nur wissen wie Material UI funktioniert.

Man muss die Rolle teilweise umbennen. 

Beispiel Fenstersensor:
Name: contact Rolle: state funktioniert nicht
Name: contact Rolle: sensor.window/sensor.door wird dann korrekt im Material UI angezeigt. 

Schau mal ein bisschen im Thread im Forum ioBroker nach, dort sind einige Beispiele.
