### ISSUE TITLE
Falscher Name bei Fibaro Motion Sensor

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [ioBroker/ioBroker.material#43]
Ich habe zwei Fibaro z-wave Motion Sensoren. Sie sind beide je einem Raum und der Function 'Bewegungsmelder' zugeordnet. Beide erscheinen auch im UI.

![image](https://user-images.githubusercontent.com/23573740/50081370-9418ac80-01ee-11e9-97a5-8639d0a7742f.png)

Allerdings wird in der 'Temperatur - Kachel' fälschlicherweise der Name 'Sesmic Intensity' generiert.
![image](https://user-images.githubusercontent.com/23573740/50081307-69c6ef00-01ee-11e9-99ba-e96c31661c5e.png)

die URL ist aber richtig 'zwave.0.NODE19.SENSOR_MULTILEVEL.Temperature_1'
Das raw-Object ist:

`{
  "from": "system.adapter.zwave.0",
  "ts": 1541777121682,
  "common": {
    "name": "Temperature",
    "type": "number",
    "role": "value.temperature",
    "unit": "C",
    "read": true,
    "write": false,
    "custom": {
      "sql.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "10000",
        "retention": "31536000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {
    "value_id": "19-49-1-1",
    "type": "decimal",
    "genre": "user",
    "label": "Temperature",
    "units": "C",
    "help": "",
    "node_id": 19,
    "class_id": 49,
    "instance": 1,
    "index": 1,
    "min": 0,
    "max": 0,
    "read_only": true,
    "write_only": false,
    "is_polled": false
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "zwave.0.NODE19.SENSOR_MULTILEVEL.Temperature_1",
  "type": "state"
}`

Seismic Intensity gibt es auch, hat natürlich eine andere URL

**Comment by emddummi** [comment]
Kannst du nicht in dem Einstellungsfenster einen eigenen Namen eingeben?
