### ISSUE TITLE
Kann kein Hintergrundbild hinzufügen

### ISSUE THREAD

**Issue by emddummi** [ioBroker/ioBroker.material#44]
Hallo, bei meinen Sonoff States kann ich Hintergrundbild hinzufügen, aber bei den Shelly States kann ich die selben Bilder nicht hinzufügen...
Mach ich irgend wie was falsch?

**Comment by emddummi** [comment]
Ich habe herausgefunden das es an Sonderzeichen im Namen liegt. Benenne ich die Datei um und ändere das im state , dann wird mir ein Bild angezeigt.

**Comment by Apollon77** [comment]
Welche Zeichen waren denn böse?

**Comment by emddummi** [comment]
Ich denke die #, Habe aus shelly.0.SHSW-1#**1D9443**#1.**R**elay**0**.Switch "background": "/material.0/admin/1D9443R0.jpg" gemacht

**Comment by emddummi** [comment]
Also die Punkte werden ersetzt, aber es bleiben immernoch die # über...

/material.0/admin/shelly_0_SHSW-1#1D8E89#1_Relay0_Switch.jpg

KA Warum die nicht ersetzt werden...

**Comment by GermanBluefox** [comment]
Fixed
