### ISSUE TITLE
Add suport of D-pad remote control 

### ISSUE THREAD

**Issue by OlegJktu** [ioBroker/ioBroker.material#46]
Please, add support of D-pad remote control. I use Android TV box and want to use material  as TV UI.
But tv remote control can work only on bottom of the page (were is mic, gears) and on instance adapter page (инстанции драйверов).

**Comment by OlegJktu** [comment]
I think  about basic support. Simple on\off and move on other.
{
  "type": "state",
  "common": {
    "name": "отопление зал",
    "type": "boolean",
    "role": "switch",
    "read": true,
    "write": true,
    "def": false,
    "desc": "Wraper state of отопление зал",
    "smartName": {
      "smartType": "THERMOSTAT"
    }
  },
  "native": {
    "group": "heating",
    "id": "0006",
    "room": "enum.rooms.living_room",
    "function": "enum.functions.heating",
    "binds": ""
  },
  "from": "system.adapter.wrapper.0",
  "ts": 1546966763139,
  "_id": "wrapper.0.heating.0006",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Apollon77** [comment]
And this is not shown? It is a normal switch. Is it also really listed in the room enum?

**Comment by OlegJktu** [comment]
It is shown. I can switch it with mouse or by tap.

But I want to switch it with remote control of  Android TV box (like Nvidia Shield remote or Fire TV remote). Remote control use DPAD_CENTER DPAD_LEFT DPAD_RIGHT DPAD_UP DPAD_DOWN.
I use [wallpanel app](https://thanksmister.com/wallpanel-android/) on Android TV. I open url of material.
But remote control of Android TV box can move and change state (on\off) only widgets on adapters page.
