### ISSUE TITLE
Add Button Support

### ISSUE THREAD

**Issue by t6a** [ioBroker/ioBroker.material#48]
A simple support for buttons is missing. I can not change all my buttons to switches. That would lead to other bigger problems.

**Comment by markuskobe** [comment]
Hi, wenn dein Device die Rolle = "button" trägt und in den Settings für das Objekt "schreiben erlaubt" = true und "lesen erlaubt" = false definiert ist, dann funktionieren Buttons super.

**Comment by GustavR** [comment]
@markuskobe I don't get this to work, could you please elaborate on your answer? Thank you very much!
