### ISSUE TITLE
Blank (white) screen at page load

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.material#5]
After installing the newest version by NPM (just used the iobroker web interface) the material web interface can be loaded but stays on an empty page.

This behaviour has been observed by using safari and chrome, below an output of chrome web inspector.

![screen shot 2018-07-16 at 12 44 27](https://user-images.githubusercontent.com/7318445/42754840-57a5bad4-88f6-11e8-9e4a-09e54b88e063.png)

**Comment by GermanBluefox** [comment]
Thank you. Fixed in the next version 0.8.7 (not yet on npm)

**Comment by Againstyou** [comment]
Also have have a white screen. Version 0.9.3. Any way to fix that? :)
Thanks!

**Comment by GermanBluefox** [comment]
>Any way to fix that? 

Any more information about it?

**Comment by Againstyou** [comment]
Its just a white screen. I opend my Firefox Developer Console and got this: 

![asd](https://user-images.githubusercontent.com/39304777/43277132-5a660a12-9107-11e8-858e-5215bbe83644.PNG)

What else can i provide to help you?

**Comment by GermanBluefox** [comment]
This is fixed now. Please retest
