### ISSUE TITLE
HTTP vs HTTPS - Seite lädt nicht über HTTPS

### ISSUE THREAD

**Issue by markuskobe** [ioBroker/ioBroker.material#50]
Hi, ich scheine ein Problem mit ioBroker.material über HTTPS zu haben...Sofern auf dem web-Adapter keine Authentifizierung und keine Verschlüsselung eingestellt ist, arbeitet ioBroker.material PERFEKT. DANKE dafür. Sobald die Verschlüsselung aktiviert wird, lädt die ioBroker.material Seite nicht mehr...bleibt im Status: lese Daten hängen...

**Comment by Ilovegym66** [comment]
funktioniert hier. Einstellungen Web-Adapter:
![screenshot_2019-02-25 instances - iobroker](https://user-images.githubusercontent.com/36229898/53354926-34dec300-3928-11e9-9566-9b37438e6d3f.png)
Welche  Versionen hast du installiert ?

**Comment by markuskobe** [comment]
Hallo Ilovegym66, danke für deine Antwort. Ich habe folgende Versionen:
Admin: 3.6.0
Cloud: 2.6.2
Socket: 2.1.1.
Material 0.10.6

Jetzt habe ich folgende Verhalten festgestellt:
Lokaler Zugriff:
HTTPs aus -> Material lädt sauber
HTTPS an, Socket integriert -> Material lädt sauber
HTTPS an, Socket o -> Material lädt NICHT (verbinden....und weiter geht es nicht)

Zugriff über ioBroker.pro
kein Zugriff, in jeglicher Konfiguration

Noch eine Idee? Danke

**Comment by Ilovegym66** [comment]
richtig, das ist bei mir genauso. - Bug

**Comment by markuskobe** [comment]
Hi, ist kein Bug! Ich habe heute mal gültige Zertifikate erstellt...das beiliegende Zertifikat beim ioBroker ist bereits 2017 abgelaufen...mit diesen GÜLTIGEN Zertifikaten funktioniert alles super. Auch mit socket.io und remote via ioBroker.pro...einziges Manko: Auf ioBroker.pro ist der Link auf material/index.html nicht vorhanden...den muss man nochmanuell im Browser ergänzen...ich mache dazu auf ioBroker.pro einen Case auf..

**Comment by markuskobe** [comment]
und auch das Link-Thema ist kein Bug...wenn man über ioBroker.pro kommt, darf die web-Instanz kein HTTPS verwenden...also web.1 angelegt mit Loopback-Adapter fürs Netzwerk, kein HTTPS und schon geht's...
