### ISSUE TITLE
Beim Scrollen auf mobilen Gerät werden unabsichtlich touch events ausgelöst

### ISSUE THREAD

**Issue by mrbjoernson** [ioBroker/ioBroker.material#55]
Bei den Feldern, z. B. zum dimmen von Licht oder einstellen der Temperatur, wird bei mobilen Geräten die entsprechende Einstellung aufgerufen, wenn ich lange mit dem Finger auf das Feld drücke. Leider geschieht dies auch, wenn ich gerade am scrollen bin und während dessen der Finger auf solch einem Feld ist. Dadurch wird unabsichtlich die Einstellung aufgerufen. Wäre schön wenn das beim scrollen nicht passiert. (Android, Chrome Beta).

PS.: Der Adapter gefällt mir sehr gut. Freue mich auf die weitere Entwicklung.

**Comment by Seraphis411** [comment]
Das Probleme habe ich auch, verwende für Material unter Android den "Fully Kiosk Browser"
