### ISSUE TITLE
Can't get the adapter to run: File 0.10.6/index.html not found: Not exists

### ISSUE THREAD

**Issue by jobe451** [ioBroker/ioBroker.material#57]
Hi 

I did setup a new iobroker-instanz on a a new raspberry pi 4 running the June 19 Raspbian with NodeJs 10.x.

I installed material UI from the "lastest" repository.

After installation I have no settings available, the icon is missing, and when I try to access the web-ui on http://mylocalserver:8082/material/0.10.6/index.html I get this error: "File 0.10.6/index.html not found: Not exists".

Web Server 2.4.1 is installed.

Some help would be appreciated.

**Comment by PrivatHomeServer** [comment]
Same here... but working with the 0.10.5 Version.

**Comment by ldittmar81** [comment]
Also!! Eine direkte Neuinstallation der Version 0.10.6 funktioniert nicht. Wenn mann aber die 0.10.5 installiert, dann mit der 0.10.6 updatet, dann geht alles.

**Comment by GermanBluefox** [comment]
Als ob upload fehlt...

**Comment by Ilovegym66** [comment]
nee, bei mir war das auch, upload hilft nicht.

**Comment by Rudi-Ment** [comment]
Gibt es hier schon eine Lösung ?

**Comment by ldittmar81** [comment]
Version 0.10.5 drauf, dann kannst du danach auf 0.10.6 updaten.

**Comment by GermanBluefox** [comment]
Please test 0.12.1

**Comment by ldittmar81** [comment]
File 0.12.1/index.html not found: Not exists :-(

Also... ich habe meine alte Version von material komplett entfernt und dann habe ich die 0.12.1 neu drauf gespielt.

**Comment by GermanBluefox** [comment]
I just have the confirmation from one other user that it runs.
Here is my installation:

![image](https://user-images.githubusercontent.com/4582016/68393119-9ddf3180-016b-11ea-8466-6d1593ff0d2d.png)

**Comment by GermanBluefox** [comment]
Are you using redis?
Will it help to execute: `npm i iobroker.material && iobroker u material` ?

**Comment by GermanBluefox** [comment]
Te Problem was fixed with the last js-controller 2.0.42.
Please verify.
`iobroker u material` will fix the problem
