### ISSUE TITLE
Schwarze Schrift im Menu

### ISSUE THREAD

**Issue by Gerrni** [ioBroker/ioBroker.material#6]
Die Menuführung auf der linken Seite lässt sich beim Standard Hintergrundbild nicht lesen. Sowohl bei Ansicht per Smartphone als auch Tablet.

**Comment by GermanBluefox** [comment]
Screenshot?

**Comment by 61stephan** [comment]
anbei ein screenshot
![material](https://user-images.githubusercontent.com/33962338/42821342-a2bc5e0a-89d8-11e8-8822-f0575d8a828c.JPG)

**Comment by Smoker2604** [comment]
HI,

das hatte ich auch. Du musst einmal die Hintergrundfarbe vom Menü auf weiß stellen. Dann passt es.

**Comment by Gerrni** [comment]
Wo genau stellt man das ein?

**Comment by Smoker2604** [comment]
Hier:
![grafik](https://user-images.githubusercontent.com/29926685/42872033-13ee7470-8a7c-11e8-8e37-42941a92f3c7.png)

**Comment by Gerrni** [comment]
Wenn das Menü fixiert ist passt es. Klick mal auf das Schloss, dann wird das Menu ausgeblendet. Lässt es dann anzeigen ist die Schrift noch schwarz.
![screenshot_20180718-124238_chrome](https://user-images.githubusercontent.com/40135870/42877054-c11b7416-8a88-11e8-9100-7d87a582b6ed.jpg)

**Comment by GermanBluefox** [comment]
Fixed in 0.8.8
