### ISSUE TITLE
Languages are wrong

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.material#60]
All languages, except en and de are wrong. It must be retranslated. I corrected it for pt on pr #59. All other languages are still wrong. 

https://github.com/ioBroker/ioBroker.material/blob/9b98d39dbfaef4b55437f31a900ddf7b9ceb657d/src/src/i18n/es.json#L159

Here for example should be WNW and not deshabilitar instancia

**Comment by GermanBluefox** [comment]
Fixed
