### ISSUE TITLE
MaterialUI does not work after installation

### ISSUE THREAD

**Issue by TeaJAge** [ioBroker/ioBroker.material#61]
In Attachement Screenshots describing the bug:
 
![image](https://user-images.githubusercontent.com/53251709/67042155-93f77f00-f127-11e9-93f6-3ed5b9d8d831.png)

![image](https://user-images.githubusercontent.com/53251709/67042170-9bb72380-f127-11e9-9dc0-9747a1d9a908.png)

![image](https://user-images.githubusercontent.com/53251709/67042184-a1146e00-f127-11e9-98fd-f5bfcc65d4e3.png)

![image](https://user-images.githubusercontent.com/53251709/67042195-a5d92200-f127-11e9-8c38-3e991c07e9cc.png)
![image](https://user-images.githubusercontent.com/53251709/67042202-ac679980-f127-11e9-9665-b2d7097caf29.png)

The machine is running in a docker container.
Do you have an idea or can I give you more Information?

**Comment by Apollon77** [comment]
iobroker upload material
tried?

**Comment by TeaJAge** [comment]
thanks, this works!
