### ISSUE TITLE
There is no way to set your own icon.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.material#64]
Version 0.12.1. loading your own icons doesn't work, you can only choose from the available ones

**Comment by Diginix** [comment]
I have the same problem. I have asked other users and they said that it works for them.
My workaround is to edit the RAW of the object and insert there the base64 icons.

**Comment by Anzic23** [comment]
Yes, this can be done, but it is not convenient. If the object belongs to the adapter, the icon will disappear when the adapter is restarted.

**Comment by Anzic23** [comment]
0.13.0 - Still not working. web 3.0

**Comment by Apollon77** [comment]
0.13.0 was not supposed to fix this ... see changelog

**Comment by GermanBluefox** [comment]
Fixed in 0.13.8
