### ISSUE TITLE
Missing developer documentation

### ISSUE THREAD

**Issue by ls2pw** [ioBroker/ioBroker.material#69]
Hi, as a react developer i would like to contribute to this adapter, but i cannot find any developer documentation or other good starting point. 

I already started by installing ioBroker locally on my machine and checked out the latest version of this adapter. What i've found is a `gulp` script including some kind of `webserver` and `watch` mode for changed files. And an `npm` script to have the adapter run standalone listening to my changes. 

What i would like to have is a connection of the (debuggable) adapter to my locally running ioBroker instance or my production version of ioBroker. How is it possible to achieve that? 

Best regards and stay healthy, 
Lars

**Comment by GermanBluefox** [comment]
```cd src
npm run start```

**Comment by ls2pw** [comment]
I'm sorry, that does not answer my question. In the meantime i switched over to use lovelace for iobroker and i'm really happy with it.
