### ISSUE TITLE
Nach Funktionszuordnung kein Objektname mehr

### ISSUE THREAD

**Issue by Smoker2604** [ioBroker/ioBroker.material#7]
Hallo,

ich habe das Problem, nachdem ich meinem Gerät eine Funktion zugeordnet habe, dass der name vom Objekt nicht mehr angezeigt wird.

Bei Funkionen die vordefiniert sind, passt das nicht.

Es hat was mit dem namen zutun. Wenn ich den Namen von Drucker auf Druckers ändere, funktioniert alles.

Ohne Funktionszuordnung:
![grafik](https://user-images.githubusercontent.com/29926685/42868094-ba8af386-8a71-11e8-910c-e4015f4fea2e.png)
Mit Funktionszuordnung:

![grafik](https://user-images.githubusercontent.com/29926685/42868105-beea41a2-8a71-11e8-9bd1-2c5c39af5239.png)

Objekt:
![grafik](https://user-images.githubusercontent.com/29926685/42868159-e5085dec-8a71-11e8-95fc-5d037c1cffda.png)

![grafik](https://user-images.githubusercontent.com/29926685/42868203-0653565a-8a72-11e8-9780-7fe270ced8b6.png)
![grafik](https://user-images.githubusercontent.com/29926685/42868217-0d5c98d0-8a72-11e8-9e41-aef9673b842b.png)

Vordefinierte Funktion:

![grafik](https://user-images.githubusercontent.com/29926685/42868376-76a0f872-8a72-11e8-984f-a434ff1aa11d.png)

**Comment by GermanBluefox** [comment]
Fixed in 0.9.3
