### ISSUE TITLE
Adapter Installation failed "Invalid version of "web". Installed "2.4.10", required ">=3.0.0"

### ISSUE THREAD

**Issue by dphotograph** [ioBroker/ioBroker.material#71]
Hello everybody, 

I run into an error when trying to install the adapter.
it requiers the version of "web" ">=3.0.0" and read my installed version as "2.4.10"
but if i check my version of "web" manually it read it right as "3.0.7"

I am not sure if it is an error or the error is between my ears.

![image](https://user-images.githubusercontent.com/9300651/81484977-3e60fc00-924a-11ea-9e8a-6b499d4d696e.png)
![image](https://user-images.githubusercontent.com/9300651/81484981-491b9100-924a-11ea-8bb9-ac605ab25af5.png)

System:
![image](https://user-images.githubusercontent.com/9300651/81485059-d1019b00-924a-11ea-9383-e1815ddd81ab.png)

Thanks :-)

**Comment by Apollon77** [comment]
welcher js-controller ist installiert?
Bitte mal "iobroker upload web" ausführen

**Comment by dphotograph** [comment]
Hi Apollon, 
Danke für die Antwort! :-) 
Ich konnte den Adapter nun auch Installieren, lag evtl. doch zwischen den Ohren.
ich habe den JS controller  2.2.9 installiert.
"iobroker upload web" habe ich ausgeführt, 
ebenfalls hatte ich bemerkt das "Material UI" nach dem letzten versuch als "installiert" angezeigt wurde und konnte den Adapter nach einem Deinstallieren nun auch erfolgreich installieren. 

Danke.
