### ISSUE TITLE
Plug Widget Popup menu 

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.material#76]
If i click on the X at the bottom it switches my SmartPlug. I think this is a bug, if not think about to change this behaviour.
Most people will think that the X is closing the popup.

Adapter Version: 1.0.0

![image](https://user-images.githubusercontent.com/16007760/125993736-d4a8734f-d7e4-483f-99ae-3e3b4dafc51b.png)

**Comment by GermanBluefox** [comment]
Please test 1.0.1
