### ISSUE TITLE
Bilder der Aufzählung zu groß

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.material#77]
Material 1.0.2

Ich habe meine Aufzählungen angepasst, neue Bilder hinzugefügt und auch eine neue Kategorie erstellt.

<img width="623" alt="enum1" src="https://user-images.githubusercontent.com/9552828/126558742-0b61d793-67e1-4f17-afe4-f75a586dd55b.png">

Leider wird das Icon meiner Kategorie bei Material nicht angezeigt, sondern nur die Bezeichnung:

<img width="185" alt="enum2" src="https://user-images.githubusercontent.com/9552828/126558883-5a33bb48-8d78-41a5-a238-f4b12e28c2fc.png">

Bei den Unterkategorien habe ich auch Bilder hinzugefügt:

<img width="308" alt="enum3" src="https://user-images.githubusercontent.com/9552828/126558957-3d53a3d0-e469-4126-a5cc-94e8e44eb882.png">

Überall werden die der Größe entsprechend angezeigt. Bei Material leider in der Original-Größe:

<img width="524" alt="enum4" src="https://user-images.githubusercontent.com/9552828/126559058-badc1647-dd43-4e06-9642-cc5e6f3b1909.png">

**Comment by Schorsch99** [comment]
Gleiches Problem bei mir.

**Comment by GermanBluefox** [comment]
> Leider wird das Icon meiner Kategorie bei Material nicht angezeigt, sondern nur die Bezeichnung:

![image](https://user-images.githubusercontent.com/4582016/126803483-4716143c-8a6e-4706-962b-180877711665.png)

Wie wird Icon gesetzt?

**Comment by Schorsch99** [comment]
Bei mir hat sich leider mit Version 1.0.3 nichts verbessert, auch nicht nach iobroker restart oder gar reboot.

![grafik](https://user-images.githubusercontent.com/27017311/126870087-296269e8-57ad-415d-9630-fd9d66d42a69.png)

**Comment by ldittmar81** [comment]
> > Leider wird das Icon meiner Kategorie bei Material nicht angezeigt, sondern nur die Bezeichnung:
> 
> ![image](https://user-images.githubusercontent.com/4582016/126803483-4716143c-8a6e-4706-962b-180877711665.png)
> 
> Wie wird Icon gesetzt?

<img width="295" alt="Screenshot 2021-07-25 115529" src="https://user-images.githubusercontent.com/9552828/126895140-583339bd-4d35-4bd4-a2c9-6f3510c7ed33.png">

Die Icons sind jetzt nur noch im Menü groß... auf der Bediensoberfläche passt es jetzt.

**Comment by GermanBluefox** [comment]
> > > Leider wird das Icon meiner Kategorie bei Material nicht angezeigt, sondern nur die Bezeichnung:
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/4582016/126803483-4716143c-8a6e-4706-962b-180877711665.png)
> > Wie wird Icon gesetzt?
> 
> <img alt="Screenshot 2021-07-25 115529" width="295" src="https://user-images.githubusercontent.com/9552828/126895140-583339bd-4d35-4bd4-a2c9-6f3510c7ed33.png">
> 
> Die Icons sind jetzt nur noch im Menü groß... auf der Bediensoberfläche passt es jetzt.

Benutze bitte "🛈" icon als UTF-8

**Comment by GermanBluefox** [comment]
Please try 1.0.4

**Comment by Schorsch99** [comment]
Danke, Größe passt jetzt wieder mit 1.0.4 :-)
