### ISSUE TITLE
Probleme beim Update von 0.13.9 auf 1.0.2

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.material#78]
Material 0.13.9 -> 1.0.2
Admin 4.2.1

Nach dem Update wurde auf der Übersichtsseite auch den Kachel mit Material aktualisiert: Die IP stimmt aber nicht. Ein Klick drauf führt zur http://0.0.0.0:8082/material/index.html

<img width="371" alt="update" src="https://user-images.githubusercontent.com/9552828/126560305-87153c5a-7095-421f-9c81-59cd1dbec0df.png">

Mit der richtigen IP ist Material erreichbar.

**Comment by Apollon77** [comment]
und Admin 5? :-)

**Comment by ldittmar81** [comment]
Update beim Admin 5, auf mein Test Server, lief ohne Probleme.

**Comment by GermanBluefox** [comment]
> Update beim Admin 5, auf mein Test Server, lief ohne Probleme.

Und ist da Link richtig?

**Comment by crunchip77** [comment]
Schließe ich mich an, selbiges Problem. Admin 5 habe ich noch nicht

**Comment by GermanBluefox** [comment]
> Schließe ich mich an, selbiges Problem. Admin 5 habe ich noch nicht

Dann ist es genau die Zeit admin5 zu benutzen

**Comment by crunchip77** [comment]
werde ich die Tage in Angriff nehmen
