### ISSUE TITLE
1.0.3: Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by justr1** [ioBroker/ioBroker.material#79]
Unter 1.0.2 und 1.0.3 lädt die Seite nicht mehr und bleibt bei "verbinden" hängen. Nach einem Downgrade auf 0.13.9 klappt es wieder.
Falls relevant: Getestet unter: Chrom und Safari, beides am Mac und am iPhone (Admin 5.1.14, Repository: beta)

Console Log:
`instrument.ts:129 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters`
`instrument.ts:129 Help us to create open source project with reactJS!`
`instrument.ts:129 See you :)`
`instrument.ts:129 Size of stored data: 855k. Max possible: 5000k`

`:8182/socket.io/?ws=true&EIO=3&transport=polling&t=NhNWxiA:1 Failed to load resource: the server responded with a status of 400 (Bad Request)`
`instrument.ts:129 Connect error: Error: xhr poll error`
`(anonymous) @ instrument.ts:129`

`:8182/socket.io/?ws=true&EIO=3&transport=polling&t=NhNWxsI:1 Failed to load resource: the server responded with a status of 400 (Bad Request)`
`instrument.ts:129 Connect error: Error: xhr poll error`
`(anonymous) @ instrument.ts:129`

Der Fehler wird dann ca. alle 5 Sekunden wiederholt.

**Comment by ericsboro** [comment]
+1

**Comment by GermanBluefox** [comment]
> +1

Auch Mac oder Iphone, ipad?

**Comment by GermanBluefox** [comment]
> Unter 1.0.2 und 1.0.3 lädt die Seite nicht mehr und bleibt bei "verbinden" hängen. Nach einem Downgrade auf 0.13.9 klappt es wieder.
> Falls relevant: Getestet unter: Chrom und Safari, beides am Mac und am iPhone (Admin 5.1.14, Repository: beta)
> 
> Console Log:
> `instrument.ts:129 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters`
> `instrument.ts:129 Help us to create open source project with reactJS!`
> `instrument.ts:129 See you :)`
> `instrument.ts:129 Size of stored data: 855k. Max possible: 5000k`
> 
> `:8182/socket.io/?ws=true&EIO=3&transport=polling&t=NhNWxiA:1 Failed to load resource: the server responded with a status of 400 (Bad Request)`
> `instrument.ts:129 Connect error: Error: xhr poll error`
> `(anonymous) @ instrument.ts:129`
> 
> `:8182/socket.io/?ws=true&EIO=3&transport=polling&t=NhNWxsI:1 Failed to load resource: the server responded with a status of 400 (Bad Request)`
> `instrument.ts:129 Connect error: Error: xhr poll error`
> `(anonymous) @ instrument.ts:129`
> 
> Der Fehler wird dann ca. alle 5 Sekunden wiederholt.

Auf welchem Port läuft WEB oder socket.io Instance?

**Comment by GermanBluefox** [comment]
Please try 1.0.4

**Comment by justr1** [comment]
1.0.4 bringt leider keine Besserung.
Port Web: 8182
Port socket.io: 8184
Hab es auch mal mit anderen Ports (8082 und 8084) versucht, ändert aber auch nichts.

**Comment by ericsboro** [comment]
I found solution for 1.0.3 - install and enable socket.io adapter and enable it in web.0 adapter. Then restart web and vis adapters and it should work :)

**Comment by justr1** [comment]
Tatsächlich! Vielen Dank! Bei mir ist es zwar nicht die web-Instanz 0 und ich nutze auch den vis nicht, aber bei mir stand die socket.io-Einstellung in der web-Instanz auf integriert ("-"). Sobald ich meine dedizierte socket.io-Instanz auswähle, klappt es. Zumindest lokal, unter iobroker.pro bekomme ich noch eine leere Seite, sobald ich die Version hochziehen will.
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/css/main.bf8ff6b7.chunk.css net::ERR_ABORTED 404 (Not Found)`
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/js/2.e5339d9a.chunk.js net::ERR_ABORTED 404 (Not Found)`
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/css/2.8c32401a.chunk.css net::ERR_ABORTED 404 (Not Found)`
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/js/main.c6bab6f4.chunk.js net::ERR_ABORTED 404 (Not Found)`
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/css/2.8c32401a.chunk.css net::ERR_ABORTED 404 (Not Found)`
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/css/main.bf8ff6b7.chunk.css net::ERR_ABORTED 404 (Not Found)`
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/js/2.e5339d9a.chunk.js net::ERR_ABORTED 404 (Not Found)`
`iobroker.pro/:1 GET https://iobroker.pro/material/1.0.4/static/js/main.c6bab6f4.chunk.js net::ERR_ABORTED 404 (Not Found)`
`DevTools failed to load source map: Could not load content for chrome-extension://dafgdjggglmmknipkhngniifhplpcldb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`
`manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.`

**Comment by GermanBluefox** [comment]
Rufe https://iobroker.pro/material/index.html auf. Und New-Material ist noch nicht für Cloud freigegeben.

**Comment by justr1** [comment]
Ja, [https://iobroker.pro/material/index.html](https://iobroker.pro/material/index.html) funktioniert, nur das Hochziehen auf [https://iobroker.pro/material/1.0.4/](https://iobroker.pro/material/1.0.4/) klappt nicht. Wenn das Absicht ist, passt das natürlich auch für mich.  ;-)
Da es lokal nun funktioniert, schließe ich das Issue.
Vielen Dank!
