### ISSUE TITLE
When changing via Wheel or such (e.g. volume) new state value is written all 2 values

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.material#8]
I saw in a log of an Alexa user that changed volume using material that the adapter got updates every "2" (so 40,42,44,46,48....) and this very fast. And all those requests were send to Alexa.

The Material UI should prevent such a dos attack ;-)

Please make sure that all such "sliding" UI elements wait till they set a value till there is no change anymore ... e.g. have 500ms/1s without a change and then send the final value.

**Comment by Ilovegym66** [comment]
additional:
I found the handling of the wheel is not nice.. the blinds and lights slider are very good in the handling.

Next thing, it's every time a surprise, how loud it is.. is 45 okay, or too loud? 
I mean a realtime change of the volume was better, if it's possible. (think the problem above..)
We have a delay, from the set of the volume, to the klick in the screen, that the number send to alexa, and the next delay is, if alexa recognize it and change the volume... 

In summery a easier handling and faster response of changes with the volume button.

**Comment by Apollon77** [comment]
Realtime no way. Not from
A such asynchronous web ui

**Comment by GermanBluefox** [comment]
Delay 300ms added
