### ISSUE TITLE
Problem with upgrade from 0.13.9

### ISSUE THREAD

**Issue by Daboompl** [ioBroker/ioBroker.material#92]
Hi i have problem with upgrade from old to new version.  Also i remove old version but nothing helping. Now i can't instal material adapter.

Log:
 
$ iobroker add material --host raspberrypi

internal/modules/cjs/loader.js:1044 throw err; ^SyntaxError: /opt/iobroker/node_modules/iobroker.material/io-package.json: Unexpected end of JSON input at parse (<anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:480:19) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:864:20) at processImmediate (internal/timers.js:463:21)

ERROR: Process exited with code 1

System:
Node.js v12.22.2
NPM v6.14.13
Installed: 3.3.22

Thanks for help

**Comment by Daboompl** [comment]
pi@raspberrypi:~ $ sudo npm install iobroker.material
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ iobroker.material@1.1.2
updated 1 package and audited 1 package in 40.386s
found 0 vulnerabilities

**Comment by Apollon77** [comment]
Pleas etry the reinstall in /opt/iobroker and not in /home/pi :-)

And IF asjon file is broken also check your SD card!

**Comment by Daboompl** [comment]
thanks i' do iobroker fix and:

cd /opt/iobroker
npm install iobroker.material
iob upload material

This help.

But i have more strange  error in Log, i must check SD card.
